.Dd July 21, 2015
.Dt sass-stack-file-context 1
.Os
.Sh NAME
.Nm sass-stack-file-context
.Nd Provide libsass file context on stack
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
This utility tests how C++ Sass library
works with user-supplied data.
.Pp
This sample program allocates Sass file context
on stack instead of using heap.
.Sh AUTHOR
Marcin Cieslak <saper@saper.info>
